### ISSUE TITLE
Emoslib EOL

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/libemos-rpm#3]
From https://confluence.ecmwf.int/display/EMOS/Emoslib:

> Please note that Emoslib has been superseded by the new interpolation routines within Metview and MARS. Please check the documentation of these tools for further information. There will be no new developments and support for Emoslib.

**Comment by edigiacomo** [comment]
Da eccodes 2.28 è stata rimossa l'opzione `GRIB_UTIL_SET_SPEC_FLAGS_ONLY_PACKING` necessaria alla compilazione di Emoslib (https://confluence.ecmwf.int/display/ECC/History+of+Changes)

**Comment by brancomat** [comment]
Emoslib rimosso da ogni uso operativo. Chiudo issue e archivio il repository.
